[build]
    command = "npm run build"
    publish = "build/"

[functions]
    directory = ".netlify/functions/"


[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true